---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(readr)
library(dplyr)

# color blind palette
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7")
```
```{r}
avatar <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-11/avatar.csv')
```
```{r}
avatar
```
```{r}
# unique(avatar$character)
```

```{r}
# filter for main protagonists 
main <- list("Aang","Zuko","Katara","Toph","Sokka","Azula","Iroh")
water <- filter(filter(avatar, character %in% main), book == "Water")
fire <- filter(filter(avatar, character %in% main), book == "Fire")
earth <- filter(filter(avatar, character %in% main), book == "Earth")
```


```{r}
ggplot(data = water, mapping = aes(x = chapter, fill = character))+
  geom_bar(position = "fill")+
  coord_flip() +
  scale_x_discrete(limits=rev(unique(water$chapter)))+
  scale_fill_manual(values=cbPalette,
                    guide = guide_legend(reverse = TRUE))+
  labs(title= 'Who spoke most frequently?',
       subtitle = "Book: Water",
       x='Episode',
       y='Percentage', 
       fill="Character:")+
  theme_minimal()+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position = 'top',
        plot.title = element_text(hjust = -0.85, vjust=-2),
        plot.subtitle = element_text(hjust = -0.51, vjust=-1),
        panel.grid.major = element_blank()
        )
```
```{r}
water
```
# Who spoke the most words?
```{r}
# count words per row in character_words
water$words <- sapply(strsplit(water$character_words, " "), length)
water_a <- aggregate(water$words, by=list(Character=water$character, Chapter=water$chapter), FUN=sum)
water_a
```
```{r}
ggplot(data=water_a, mapping = aes(x = Chapter, 
                                   y = x, 
                                   color = Character))+
  geom_point()+
  theme_minimal()+
  scale_x_discrete(limits=rev(unique(water$chapter)))+
  labs(x='Episode', 
       y='Words spoken',
       title='Who spoke the most words?',
       subtitle="Book: Water")+
  scale_color_manual(values=cbPalette,
                    guide = guide_legend(reverse = TRUE))+
  theme(plot.title = element_text(hjust = -1.5, vjust=-2),
        plot.subtitle = element_text(hjust = -0.7, vjust=-1.2),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())+
  coord_flip()
```
```{r}
# Which chapter has the most dialog?
water_b <- aggregate(water_a$x, by=list(Chapter=water_a$Chapter), FUN=sum)
water_b
```
```{r}
ggplot(mapping = aes(x = water_b$Chapter, y = water_b$x))+
  geom_segment(mapping =aes(x = water_b$Chapter, xend = water_b$Chapter, y=0, yend=water_b$x-20), color="56B4E9") +
  geom_point( color="#0072B2", size=4, alpha=0.6) +
  scale_x_discrete(limits=rev(unique(water$chapter)))+
  labs(title = 'Which chapter has the most dialog?',
       subtitle = 'Book: Water',
       x = 'Episode',
       y = 'Dialog [in Words]')+
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank(),
    plot.title = element_text(hjust = -1.2, vjust=-1),
    plot.subtitle = element_text(hjust = -0.535, vjust=-1.0),
    panel.grid.minor = element_blank())
```
